{% set name = "django-admin-multi-select-filter" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_admin_multi_select_filter-{{ version }}.tar.gz
  sha256: 029bc1e2c64f181979a01706efc2c37d2f0da2e85276ad495a20e9d49167aa53

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.0
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.0
    - django >=3

test:
  imports:
    - django_admin_multi_select_filter
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Django admin filter for multiple select
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gb119
